apiVersion: v1
kind: DeploymentConfig
metadata:
  name: gitlab-runner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: gitlab-runner
      labels:
        app: gitlab-runner
    spec:
      serviceAccount: gitlab-runner
      containers:
      - name: run
        image:  quay.io/openshift-examples/gitlab-runner:latest
        command:  
          - /usr/bin/bash
          - -x
          - -c
          - |
            # Register 
            cp -v /gitlab-runner-config/config.toml $HOME/.gitlab-runner/config.toml

            gitlab-runner unregister --all-runners
            # unregister do not update config.toml if unregister fail.
            rm $HOME/.gitlab-runner/config.*

            gitlab-runner register --non-interactive

            # Update secret
            oc create secret generic gitlab-runner-config  --from-file=config.toml=$HOME/.gitlab-runner/config.toml --dry-run -o yaml | oc apply -f -

            gitlab-runner run
        volumeMounts:
        - name: gitlab-runner-config
          mountPath: "/gitlab-runner-config"
          readOnly: true
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - secretRef:
            name: gitlab-runner-register
        livenessProbe:
          exec:
            command:
            - /usr/bin/bash
            - -x
            - -c
            - |
              # gitlab-runner verify wont work with $CI_SERVER_URL
              unset CI_SERVER_URL
              gitlab-runner verify
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: gitlab-runner-register
        secret:
          secretName: gitlab-runner-register
      - name: gitlab-runner-config
        secret:
          secretName: gitlab-runner-config
  triggers:
  - type: ConfigChange