apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: nginx
  namespace: myproject
spec:
  replicas: 1
  strategy:
    type: Recreate
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
  triggers:
  - type: ConfigChange 