apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: pythonex
  labels:
    name: pythonex
spec:
  triggers:
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: 'https://github.com/catsy00/pythonex.git'
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'pythonex:latest'