apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

# oc set volume deployment/httpd --add --name=httpd-volume-1 -t pvc --claim-name=httpd --mount-path=/var/www/html/