apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pythonex
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 200Gi
  nfs:
    path: "/nfs_storage/3scale1"
    server: "nfs.ocp44.sschoiwith.com"
  persistentVolumeReclaimPolicy: Recycle