kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/catsy00/pythonex.git'
    openshift.io/generated-by: OpenShiftWebConsole
  namespace: myproject
  labels:
    app: pythonex-git
    app.kubernetes.io/component: pythonex-git
    app.kubernetes.io/instance: pythonex-git
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: pythonex-git-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: '3.6'
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'pythonex-git:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.6'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/catsy00/pythonex.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: pythonex-git-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: pythonex-git-github-webhook-secret
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/python@sha256:f49e1f9d577dd3da34a1273e46fe8539274648d27851c41da47642f539148043
    - type: ConfigChange
  runPolicy: Serial