apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  namespace: myproject
  labels:
    app.kubernetes.io/instance: pythonex-git
    pipeline.openshift.io/runtime: python
    pipeline.openshift.io/type: openshift
spec:
  params:
    - default: pythonex-git
      name: APP_NAME
      type: string
  resources:
    - name: app-source
      type: git
    - name: app-image
      type: image
  tasks:
    - name: build
      params:
        - name: TLSVERIFY
          value: 'false'
      resources:
        inputs:
          - name: source
            resource: app-source
        outputs:
          - name: image
            resource: app-image
      taskRef:
        kind: ClusterTask
        name: s2i-python-3
    - name: deploy
      params:
        - name: ARGS
          value:
            - rollout
            - status
            - dc/$(params.APP_NAME)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client